# Generated by Django 3.0.1 on 2019-12-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(blank=True, default='', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
